import Head from 'next/head';

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>create-permaweb-app App</title>
        <meta name="description" content="Generated by npx create-permaweb-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header style={{ padding: '1rem' }}>

      </header>

      <main
        style={{
          minHeight: '60vh',
          flex: '1',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >

      </main>
    </div>
  );
}
